//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int IdAnswer { get; set; }
        public int IdQuestion { get; set; }
        public string Content { get; set; }
        public bool isTrue { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
